borg backup script done

diff --git a/.local/bin/borg-mybackup b/.local/bin/borg-mybackup
--- a/.local/bin/borg-mybackup
+++ b/.local/bin/borg-mybackup
@@ -12,7 +12,6 @@ calc_next_index () {
         echo "$2-$INDEX is an existing archive. Aborting."
         exit 1
     fi
-    echo "$INDEX"
 }
 
 if [[ $EUID -ne 0 ]] ; then
@@ -34,32 +33,79 @@ BORG_CMD='borg create -xspC zstd'
 BASE_PATH_ROOT='/mnt/borg-bkup-root'
 BASE_PATH_USER='/mnt/borg-bkup-user'
 
-# check if disk is connected
-# check if not already opened
-#cryptsetup open /dev/disk/by-uuid/d2ab6a0d-333d-4726-b461-ca663042bafd bkup0
+# check if backup disk is connected
+if [[ ! -h /dev/disk/by-uuid/d2ab6a0d-333d-4726-b461-ca663042bafd ]] ; then
+    echo "No Backup disk found. Aborting."
+    exit 1
+fi
 
-# check if nothing is mounted at /mnt
-# check if disk exists
-#mount /dev/disk/by-uuid/79d55b92-46c5-4dde-90a4-abbe19903c02 /mnt
+# try to open backup disk
+if [[ ! -h /dev/disk/by-uuid/79d55b92-46c5-4dde-90a4-abbe19903c02 ]] ; then
+    # check if nothing is mounted at /mnt
+    if [[ -n "$(findmnt /mnt)" ]] ; then
+        echo "There is something mounted at /mnt. Aborting."
+        exit 1
+    fi
+
+    echo "Crpytsetup open: bkup0"
+    cryptsetup open /dev/disk/by-uuid/d2ab6a0d-333d-4726-b461-ca663042bafd bkup0
+    sleep 0.2 # wait to create the symlinks and stuff
+
+    # check if disk exists
+    if [[ ! -h /dev/disk/by-uuid/79d55b92-46c5-4dde-90a4-abbe19903c02 ]] ; then
+        echo "Failed opening backup disk. Aborting."
+        exit 1
+    fi
+fi
+
+# try to mount backup disk
+BKUPMNT="$(findmnt UUID='79d55b92-46c5-4dde-90a4-abbe19903c02' || true)"
+if [[ -z "$(echo "$BKUPMNT" | grep '/mnt')" ]] ; then
+    if [[ -n "$(findmnt /mnt)" ]] ; then
+        echo "There is something else mounted at /mnt. Aborting."
+        exit 1
+    fi
+
+    if [[ -n $BKUPMNT ]] ; then
+        echo "Backup disk is already mounted somewhere else. Aborting."
+        exit 1
+    fi
+
+    mount /dev/disk/by-uuid/79d55b92-46c5-4dde-90a4-abbe19903c02 /mnt
+    if [[ -z "$(findmnt UUID='79d55b92-46c5-4dde-90a4-abbe19903c02' | grep '/mnt')" ]] ; then
+        echo "Failed to mount. Aborting."
+        exit 1
+    fi
+fi
 
 ROOT_REPO_BKUPS="$(borg list $BASE_PATH_ROOT)"
 USER_REPO_BKUPS="$(su -c "borg list $BASE_PATH_USER" - daniel)"
 
 cd /boot
 calc_next_index "$ROOT_REPO_BKUPS" "$ARCHIVE_HOST-boot"
-#$BORG_CMD "$BASE_PATH_ROOT::$ARCHIVE_HOST-boot-$INDEX" .
+$BORG_CMD "$BASE_PATH_ROOT::$ARCHIVE_HOST-boot-$INDEX" .
 
 cd /.btrfs/@
 calc_next_index "$ROOT_REPO_BKUPS" "$ARCHIVE_HOST-root"
-#$BORG_CMD "$BASE_PATH_ROOT::$ARCHIVE_HOST-root-$INDEX" .
+$BORG_CMD "$BASE_PATH_ROOT::$ARCHIVE_HOST-root-$INDEX" .
 
 cd /.btrfs/@home
 calc_next_index "$USER_REPO_BKUPS" "$ARCHIVE_HOST-home-daniel"
-#su -c "$BORG_CMD $BASE_PATH_USER::$ARCHIVE_HOST-home-daniel-$INDEX ." - daniel
+su -c "$BORG_CMD $BASE_PATH_USER::$ARCHIVE_HOST-home-daniel-$INDEX ." - daniel
 
-#borg list "$BASE_PATH_ROOT"
-#su -c "borg list $BASE_PATH_USER" - daniel
+borg list "$BASE_PATH_ROOT"
+echo ""
+su -c "borg list $BASE_PATH_USER" - daniel
 
-#umount /mnt
-#vgchange -an vgb0
-#cryptsetup close bkup0
+while true; do
+    read -p 'Try to eject the backup disk? [y/n] ' YN
+    case "$YN" in
+        [YyJj] ) break;;
+        [Nn]   ) exit 0;;
+        *      ) echo "Please answer yes or no [y/n].";;
+    esac
+done
+
+umount /mnt
+vgchange -an vgb0
+cryptsetup close bkup0
